FROM golang:1.13.3-alpine3.10@sha256:40278d43a27b6e0563fcc4dd52c991a25741b1a775402aea342ab9a80158e69e as builder

ENV GOPATH /go
ENV USER root

COPY . /go/src/github.com/cloudflare/cfssl

RUN set -x && \
	apk --no-cache add git gcc libc-dev make

RUN set -x && \
	apk --no-cache add git gcc libc-dev && \
	go get github.com/cloudflare/cfssl_trust/... && \
	go get github.com/GeertJohan/go.rice/rice && \
	cd /go/src/github.com/cloudflare/cfssl && rice embed-go -i=./cli/serve && \
	mkdir -p bin && cd bin && \
	go build ../cmd/cfssl && \
	go build ../cmd/cfssljson && \
	go build ../cmd/mkbundle && \
	go build ../cmd/multirootca && \
	echo "Build complete."

FROM alpine:3.10
COPY --from=builder /etc/cfssl /etc/cfssl
COPY --from=builder /workdir/bin/ /usr/bin

EXPOSE 8888

ENTRYPOINT ["cfssl"]
CMD ["--help"]