FROM golang:1.13-alpine

ENV GOPATH /go
ENV USER root

WORKDIR /go/src/github.com/cloudflare/cfssl
COPY . .

# restore all deps and build
RUN set -x && \
    apk --no-cache add git gcc libc-dev && \
    go get github.com/cloudflare/cfssl_trust/... && \
    go get github.com/GeertJohan/go.rice/rice && \
    cd /go/src/github.com/cloudflare/cfssl && \
    rice embed-go -i=./cli/serve/ && \
    cp -R /go/src/github.com/cloudflare/cfssl_trust /etc/cfssl && \
    go install ./cmd/...

EXPOSE 8888

ENTRYPOINT ["cfssl"]
CMD ["--help"]
